/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'nvonop' at '15/05/16 22:29' with Gradle 2.10
 *
 * @author nvonop, @date 15/05/16 22:29
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
