/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'nvonop' at '15/05/16 22:29' with Gradle 2.10
 *
 * @author nvonop, @date 15/05/16 22:29
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
